name: quick-flow
description: Quick assessment and setup for brownfield projects - skip lengthy PRD, go straight from requirements to context-aware technical specs
version: 1.0.0

workflow_type: assessment
input_file: "{project-root}/docs/bmm-workflow-status.yaml"

steps:
  - id: project_scan
    name: Scan Project Structure
    action: scan_codebase
    checks:
      - check: file_structure
        description: "Analyze project file structure and organization"
      - check: dependencies
        description: "Review package.json and dependencies"
      - check: configuration_files
        description: "Check build and config files"
    
  - id: identify_issues
    name: Identify Critical Issues
    action: identify_blockers
    checks:
      - check: missing_files
        description: "Find missing imports and files"
      - check: broken_references
        description: "Check for broken component references"
      - check: build_errors
        description: "Identify potential build/runtime errors"
    
  - id: assess_codebase
    name: Assess Codebase State
    action: assess_quality
    metrics:
      - code_organization
      - component_structure
      - type_safety
      - configuration_completeness
    
  - id: generate_assessment
    name: Generate Quick Assessment Report
    action: generate_report
    template: quick_assessment
    output: "{project-root}/docs/quick-flow-assessment.md"
    sections:
      - project_overview
      - structure_analysis
      - issues_found
      - recommendations
      - next_steps
    
  - id: update_status
    name: Update Workflow Status
    action: update_status_file
    file: "{project-root}/docs/bmm-workflow-status.yaml"
    update:
      workflow_status:
        quick-flow:
          status: completed
          completed_at: "{timestamp}"
          report: "docs/quick-flow-assessment.md"

output:
  format: markdown
  location: "{project-root}/docs/quick-flow-assessment.md"
  save_after_each_section: true

